Fixed indentation and looping example

diff --git a/menugencli b/menugencli
--- a/menugencli
+++ b/menugencli
@@ -5,18 +5,18 @@
 # $2 - Prompt text (a string)
 # $3 - Auto-selection option (a boolean)
 function RENDERMENU() {
-    if [[ $# -ne 3 ]]; then
-	>&2 echo "ERROR: RENDERMENU requires 3 arguments (got $#)"
-	>&2 echo "    - The menu content (value: \"$1\")"
-	>&2 echo "    - The prompt text (value: \"$2\")"
-	>&2 echo "    - Boolean for autoselect (value: \"$3\")"
-	exit -1
-    fi
-    if [[ "$3" == true ]]; then
-	echo -e "$1" | fzf --reverse --select-1 --prompt="$2"
-    else
-	echo -e "$1" | fzf --reverse --prompt="$2"
-    fi
+	if [[ $# -ne 3 ]]; then
+		>&2 echo "ERROR: RENDERMENU requires 3 arguments (got $#)"
+		>&2 echo "    - The menu content (value: \"$1\")"
+		>&2 echo "    - The prompt text (value: \"$2\")"
+		>&2 echo "    - Boolean for autoselect (value: \"$3\")"
+		exit -1
+	fi
+	if [[ "$3" == true ]]; then
+		echo -e "$1" | fzf --reverse --select-1 --prompt="$2"
+	else
+		echo -e "$1" | fzf --reverse --prompt="$2"
+	fi
 }
 
 source menugenbase
